theme: minima
title: Kapila's Site
author: Kapila Mane
email: manekapila@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Kapila Mane's Github site.

# social links
instagram_username: kapila.mane
github_username:  cupmaine # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
